config/routes.rb
Rails.application.routes.draw do

  root 'estatesales#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :estatesales do
    resources :images, :only => [:create, :destroy]
  end
  resources :favorite_sales
  resources :users
  get 'companies' => 'companies#index'
  get 'list' => 'estatesales#list'  # to advertise/list a sale

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/estatesale.rb
class Estatesale < ActiveRecord::Base
  validates_presence_of :title, :address, :city, :state, :zip_code, :start_date, :end_date, :times, :description, :forms_of_payment
  validates :title, uniqueness: true
  geocoded_by :full_address
  after_validation :geocode

# For Carrierwave photos:
  attr_accessor :photos
  mount_uploaders :images, ImagesUploader
  serialize :images, JSON


  belongs_to :lister
  has_many :favorites
  has_many :shoppers, through: :favorites


# To determine distance from zip code input:
  def distance_from(from)
    GoogleDistanceService.get_distance(from, full_address).round(2)
  end

  def full_address
    [address, city, state, zip_code].join(", ")
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  # belongs_to :shopper
  # belongs_to :estatesale
  belongs_to :favorited, polymorphic: true
  belongs_to :user

  #######
  belongs_to :shopper

end

app/models/lister.rb
class Lister < User
  #added
  has_many :estatesales
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorites
end

app/models/shopper.rb
class Shopper < User
  #added
  # has_many :favorites
  # has_many :estatesales, through: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :username, :password, :email
  validates_uniqueness_of :username, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "Please enter a valid email address."
  validates_length_of :username, :minimum => 3, :message => "Username must be at least 3 characters."
  validates_length_of :password, :in => 6..20, :message => "must be between 6-20 characters."
  has_secure_password

  # Added:
  has_many :favorites
  has_many :favorite_sales, through: :favorites, source: :favorited, source_type: 'Estatesale'

  has_many :notes, through: :favorites


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # makes methods available to views:
   helper_method :current_user, :logged_in?, :admin?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Returns the current logged-in user, if any.
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns T if the user is logged in; F otherwise.
  def logged_in?
    !current_user.nil?
  end

  def admin?
    current_user && current_user.admin?
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
end

app/controllers/estatesales_controller.rb
class EstatesalesController < ApplicationController
  def index
    @sales = Estatesale.all
  end

  def show
    @sale = Estatesale.find(params[:id])
  end

  def new
    @sale = Estatesale.new
  end

  def edit
    @sale = Estatesale.find(params[:id])
  end

  def create
    @sale = Estatesale.new(estatesale_params)
    # respond_to do |format|
      if @sale.save
        # format.html { redirect_to @sale, notice: 'Sale was successfully published.'}
        # format.json { render :show, status: :created, sale: @sale}
      redirect_to @sale
      else
        render 'new'
      end
    # end
  end

  def update
    @sale = Estatesale.find(params[:id])

    if @sale.update(estatesale_params)
      redirect_to @sale
    else
      render 'edit'
    end
  end

  def destroy
    @sale = Estatesale.find(params[:id])
    @sale.destroy

    redirect_to estatesales_path
  end

  def list
    render :advertise
  end

  private
    def estatesale_params
      params.require(:estatesale).permit(:featured_image, :title, :address, :city, :state, :zip_code, :start_date, :end_date, :times, :description, :forms_of_payment, :special_inst, {images: []})
    end

end

app/controllers/favorite_sales_controller.rb
class FavoriteSalesController < ApplicationController
  before_action :set_sale

  def index
    @favorites = current_user.favorite_sales
    # @fav = Favorite.where(favorited_id: @sale.id, user_id: current_user.id)
    @sale = Estatesale.find(params[:sale_id] || params[:id])
  end

  def show
    @favorites = current_user.favorite_sales
  end

  def create
    if Favorite.create(favorited: @sale, user: current_user)
      respond_to do |format|
        format.html { redirect_to @sale, notice: 'Sale has been added to favorites!'}
        format.js
      end
    else
      redirect_to @sale, alert: 'Something went wrong!'
    end
  end

  def destroy
    Favorite.where(favorited_id: @sale.id, user_id: current_user.id).destroy
    redirect_to favorite_sales_path, notice: 'Sale is no longer in favorites'
  end

  private

  def set_sale
    @sale = Estatesale.find(params[:sale_id] || params[:id])
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_estate_sale

  def create
    add_more_images(images_params[:images])
    flash[:error] = "Failed uploading images" unless @sale.save
    redirect_to :back
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    flash[:error] = "Failed to delete image." unless @sale.save
    redirect_to :back
  end

  private

  def set_estate_sale
    @sale = Estatesale.find(params[:id])
  end

  def add_more_images(new_images)
    images = @sale.images
    images += new_images
    @sale.images = images
  end

  def remove_image_at_index(index)
    remaining_images = @sale.images # copy the array
    deleted_image = remaining_images.delete_at(index) # delete the target image
    # deleted_image.try(:remove!) # delete image from S3
    @sale.images = remaining_images # re-assign back
  end

  def images_params
    params.require(:estatesale).permit({images: []})
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @note = Note.new
  end

  def create
    if Note.create(favorited: @sale, user: current_user)
      redirect_to favorite_sales_path
    end
  end

  def edit
  end

  def delete
  end

  private

    def note_params
      params.require(:note).permit(:description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create  #creates session for returning user
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      respond_to do |format|
        format.html { redirect_to estatesales_path }
        format.json
      end
    else
      # flash.now[:danger] = 'Invalid email/password combination'
      render 'new'  #goes to sessions/new
    end
  end

  def destroy  #logs out user
    session[:user_id] = nil
    redirect_to estatesales_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   #Sign Up For New Users
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to estatesales_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:type, :username, :password, :email, :company_name, :owner_name, :company_url, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/estatesale_helper.rb
module EstatesaleHelper



end

app/helpers/favorite_sales_helper.rb
module FavoriteSalesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper

   # Returns the current logged-in user, if any.
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns T if the user is logged in; F otherwise.
  def logged_in?
    !current_user.nil?
  end

end

app/views/companies/index.html.erb
<h2>Estate Sale Companies</h2>

<% @companies.each do |company| %>
  <p><%= company.company_name %></p>
  <p><%= company.owner_name %></p>
  <p><%= company.company_url %></p>
  <p><%= company.phone_number %></p>
  <hr>
<% end %>

app/views/estatesales/_form.html.erb
<!-- New sale listing form:  -->

<div class="sale-form">
  <%= form_for(@sale) do |f| %>
    <%= if @sale.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@sale.errors.count, "error") %>
          prohibited this sale from being saved:</h2>
        <ul>
          <% @sale.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>

<!--  Company Name
 Company_Url -->

  <p>
    <%= f.label :address %>
     <%= f.text_field :address %>
  </p>
  <p>
    <%= f.label :city %>
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %>
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </p>
  <p>
    <%= f.label :start_date %>
    <%= f.text_field :start_date %>
  </p>
  <p>
    <%= f.label :end_date %>
    <%= f.text_field :end_date %>
  </p>
  <p>
    <%= f.label :times %>
    <%= f.text_field :times %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_area :description, rows: 20 %>
  </p>
  <p>
    <%= f.label :forms_of_payment %>
    <%= f.text_field :forms_of_payment %>
  </p>
  <p>
    <%= f.label :special_inst %>
    <%= f.text_field :special_inst %>
  </p>
  <!-- Need ability to upload images:  -->
  <p>
    <%= f.label :img_url %>
    <%= f.text_field :img_url %>
  </p>
  <p>
   <!--  Change button text here -->
    <%= f.submit %></p>
    <% end %>
  <br>
  <%= link_to 'Back', estatesales_path %>
</div>

app/views/estatesales/advertise.html.erb
<h2>Advertise your sales with Estates-to-Date.com!</h2>
<br>
<p class="lead">We offer several options for companies listing their sales and for individuals seeking to privately list a single sale. Select the option below that best describes you: </p>
<br>
<div class="row">
  <div class="col-md-6">
    <%= link_to new_estatesale_path do %>
    <div class="card card-inverse card-1">
      <%= image_tag("private_sale.png", class: "card-img") %>
      <div class="card-img-overlay">
        <h3 class="card-title">I'm an individual hosting a sale.</h3>
      </div>

    </div>
     </div>
    <% end %>


  <div class="col-md-6">
    <a href="#">
      <div class="card card-inverse card-2">
      <%= image_tag("company_sale.jpg", class: "card-img, company-image") %>
       <div class="card-img-overlay">
        <h3 class="card-title">I'm a company that hosts sales.</h3>

      </div>

    </div>
  </a>
  </div>
</div>

app/views/estatesales/edit.html.erb
<!-- EDIT SALE LISTING FORM -->

<h2 class="text-center">Edit Listing</h2>
<br>
<div class="row">
  <div class="col-md-12">

<%= form_for @sale, method: :patch do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %>
        prohibited this sale from being saved:</h2>
      <ul>
        <% @sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

<!-- FEATURED PHOTO: -->
  <div class="field form-group">
     <%= f.label :featured_photo, 'Featured Photo' %>
     <%= image_tag(:featured_photo) %>
     <%= f.file_field :featured_photo, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control'  %>
  </div>

<!--  Company Name
 Company_Url -->

  <div class="field form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :times %>
      <%= f.text_field :times, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 20 %>
  </div>
  <div class="field form-group">
      <%= f.label :forms_of_payment, 'Accepted forms of payment' %>
      <%= f.text_field :forms_of_payment, class: 'form-control', rows: 3 %>
  </div>
  <div class="field form-group">
      <%= f.label :special_inst, 'Special Instructions' %>
      <%= f.text_field :special_inst, class: 'form-control', rows: 10 %>
  </div>
  <div class="field form-group">
      <%= f.label :images, 'Photos' %>
      <% @sale.images.each do |image| %>
        <%= image_tag(image.url(:thumb)) %>
      <% end %>
      <%= f.file_field :images, multiple: true, class: 'form-control' %>
  </div>


  <br>

  <div class="actions form-group">
    <%= f.submit "Update Sale Listing", class: 'btn btn-default' %>
  </div>
  <% end %>


  <h4><%= link_to 'Back', estatesales_path %></h4>


  </div>
</div>

app/views/estatesales/index.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<!-- Should welcome both user types -->
<% if logged_in? %>
<h1 class="text-center">Welcome, <%= current_user.username %>!</h1>
<% end %>
   </div>
</div>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
<!-- Zip code search form -->
    <div class="well">
      <p>Search for sales in you area by zip code:</p>
      <%= form_tag("/estatesales", method: "get") do %>
        <%= label_tag(:zip_code, "Zip Code:") %>
        <%= text_field_tag(:zip_code) %>
        <%= submit_tag("Search") %>
      <% end %>
    </div>
  </div>
</div>

<div class="sales-container">
<div class="row">
  <div class="col-md-12">

  <h2 class="text-center">Current Sales & Auctions: </h2>
  <table class="table table-hover table-responsive">
    <thead class="thead-default">
      <tr>
        <td></td>
        <td><h3><strong>Dates / Times</strong></h3></td>
        <td><h3><strong>Company / Name</strong></h3></td>
        <td><h3><strong>Location</strong></h3></td>
        <td><h3><strong>Distance</strong></h3></td>
      </tr>
    </thead>
    <tbody>
      <hr>
      <% @sales.each do |sale| %>
      <tr>
        <td><%=sale.featured_photo do %>
              <%= image_tag("sale.featured_photo") %>
            <% end %>
        </td>
        <td><%=sale.start_date%> - <%=sale.end_date%><br><%=sale.times%></td>
        <td><%= link_to sale.title, estatesale_path(sale) %><br>Lasted updated: <%=sale.updated_at.strftime("%m.%d.%y")%></td>
        <td><%=sale.address%><br><%=sale.city%>, <%=sale.state%>  <%=sale.zip_code%></td>
        <td>
          <% if params[:zip_code].present? %>
            <%= sale.distance_from(params[:zip_code]) %> miles
          <% end %>
        </td>
      </tr>

      <%end%>
    </tbody>
  </table>
</div>
</div>
</div>

app/views/estatesales/new.html.erb
<!-- NEW SALE LISTING FORM (for individuals) -->
<h3>What's included with your private sale listing:</h3
<ul>
  <li>Unlimited description space</li>
  <li>First 50 pictures free</li>
  <li>Email notifications</li>
  <li>Secure mapping service</li>
</ul>
<h3>How to get started!</h3>
<ol>
  <li>Contact us for pricing information.</li>
  <li>Fill out all the details about your sale in the form below.</li>
  <li>Upload photos of the sale.</li>
</ol>
<br>
<h2 class="text-center">New Sale Listing Form</h2>
<br>
<div class="row">
  <div class="col-md-12">

<%= form_for @sale do |f| %>

  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %>
        prohibited this sale from being saved:</h2>
      <ul>
        <% @sale.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

  <!-- FEATURED PHOTO: -->
  <div class="field form-group">
     <%= f.label :featured_photo, 'Featured Photo' %>
     <%= image_tag(:featured_photo) %>
     <%= f.file_field :featured_photo, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :title, 'Title (give your sale a name)' %>
      <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :city %>
      <%= f.text_field :city, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :state %>
      <%= f.text_field :state, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :zip_code %>
      <%= f.text_field :zip_code, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :start_date %>
      <%= f.date_field :start_date, class: 'form-control' %>
  </div>
  <div class="field form-group">
      <%= f.label :end_date %>
      <%= f.date_field :end_date, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :times %>
      <%= f.text_field :times, class: 'form-control' %>
  </div>

  <div class="field form-group">
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 20 %>
  </div>
  <div class="field form-group">
      <%= f.label :forms_of_payment, 'Accepted forms of payment' %>
      <%= f.text_field :forms_of_payment, class: 'form-control', rows: 3 %>
  </div>
  <div class="field form-group">
      <%= f.label :special_inst, 'Special Instructions' %>
      <%= f.text_field :special_inst, class: 'form-control', rows: 10 %>
  </div>
  <div class="field form-group">
      <%= f.label :images, 'Photos' %>
      <%= f.file_field :images, multiple: true, class: 'form-control' %>
  </div>

  <br>

  <div class="actions form-group">
    <%= f.submit "Publish Sale Listing", class: 'btn btn-default' %>
  </div>
  <% end %>

  <h4><%= link_to 'Back', estatesales_path %></h4>

  </div>
</div>

app/views/estatesales/show.html.erb
<!-- INDIVIDUAL ESTATE SALE -->

<div class="row">
  <div class="col-md-6">
    <h3><%= @sale.title %></h3>
    <p><%= @sale.lister %></p>
    <p class="lead"><%= @sale.address %></p>
    <p class="lead"><%= @sale.city%>, <%=@sale.state%> <%= @sale.zip_code %></p>
    <p class="lead"><%= @sale.start_date %> - <%= @sale.end_date %></p>
    <p class="lead"><%= @sale.times %></p>
  </div>

   <div class="col-md-6">
      <div id="map-canvas">
        Google Map Inset
      </div>
  </div>
</div>

      <!-- AJAX CALLS NEED TO ADD: -->
      <!--  div id = star container -->
      <!--  div id = favorites container  -->
<br>
<br>
<div class="row">
  <div class="col-md-6">
    <div class="company-info">
      <ul>
        <li>Company Logo</li>
        <li>Name</li>
        <li>Phone Number</li>
        <li>Website</li>
      </ul>
    </div>
  </div>
  <div class="col-md-6">
    <div class="favorites-container">
  <!-- Add sale to favorites -->
        <% if !logged_in? %>
          <button type="button" class="btn btn-default" data-toggle="modal" data-target="#loginModal"><i id="empty" class="icon icon-star-o icon-2x"></i> Add this Sale to Favorites</button>
            <!-- Modal -->
            <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h3 class="modal-title" id="exampleModalLabel">Log In</h3>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <div class="row">
                     <div class="col-md-6 col-md-offset-3">
                       <!--  <h3 class="text-center">Log In</h3> -->
                          <%= form_for(:session, url: login_path, html: {class: 'form-horizontal'}) do |f| %>
                            <div class="field form-group">
                              <%= f.label :username, class: 'control-label' %>
                            <div class="col-md-10">
                              <%= f.text_field :username, class: 'form-control' %>
                            </div>
                            </div>
                            <div class="field form-group">
                              <%= f.label :password, class: 'control-label' %>
                            <div class="col-md-10">
                              <%= f.password_field :password, class: 'form-control' %>
                            </div>
                            </div>
                            <div class="actions form-group text-center">
                              <%= f.submit "Log In", class: 'btn btn-default' %>
                            </div>
                          <% end %>

                        <h4 class="text-center">New User? <%= link_to 'Sign up now!', new_user_path %></h3>
                        <br>
                        <h4 class="text-center"><%= link_to 'Back', :back %></h4>
                      </div>
                    </div>

                  </div>
                </div>
              </div>
            </div>

        <% end %>


        <% if logged_in? %>
          <%- unless current_user.favorite_sales.exists?(id: @sale.id) -%>
            <%= link_to favorite_sales_path(sale_id: @sale), method: :post, class: 'btn btn-default add-fav' do %>
              <i id="empty" class="icon icon-star-o icon-2x"></i>
              <i id="filled" class="icon icon-star icon-3x"></i>
              Add this Sale to Favorites
            <% end %>
        <% end %>
  <!-- See all favorites link -->
          <p class="lead">
            <%= link_to 'See all favorites', favorite_sales_path(sale_id: @sale), class: 'btn btn-default' %>
          </p>
      <% end %>

        <% if notice %>
          <p id="notice"><%= notice %></p>
        <% end %>




    </div>


  </div>
</div>
<div class="row">
  <div class="col-md-12">
     <!-- Individual Sale Details: -->
        <div id="sale-container" data-address="<%= @sale.address %>, <%= @sale.city%>, <%= @sale.state %>, <%= @sale.zip_code %>">


          <h3>Description:</h3>
          <p class="lead"><%= @sale.description %></p>
          <h3>Forms of Payment Accepted: </h3><p><%= @sale.forms_of_payment %></p>
          <h3>Special Instructions: </h3><p><%= @sale.special_inst %></p>

      <!-- PHOTOS OF SALE -->
          <h3>Photos:</h3>

            <% @sale.images.each_with_index do |image, index| %>
             <!-- link needed for fancybox usage -->
              <%= link_to image.url, {:class => "grouped_elements", :rel => "one_sale"} do %>
                <%= image_tag(image.url(:thumb)) %>
              <% end %>

              <%= link_to "Delete", estatesale_image_path(image, index), :method => :delete, data: { confirm: "Are you sure you want to delete this image?" } %>
            <% end %> <!-- end of each_with_index loop -->

      <h3>
        <%= link_to 'Back', estatesales_path %>
      </h3>

    <!-- Edit listing button (ONLY IF ADMIN!):  -->
    <% if admin? %>
      <h3>
        <%= link_to 'Edit this Listing', edit_estatesale_path(@sale) %>
      </h3>

    <!-- Delete listing button (ONLY IF ADMIN!):  -->
      <h3>
        <%= link_to 'Delete', @sale, method: :delete, data: { confirm: 'Are you sure?' } %>
      </h3>
    <% end %>
    </div>
  </div>
</div>

<script type='text/javascript'>
  var map;
  function initMap() {

      var location = {lat: <%= @sale.latitude %>, lng: <%= @sale.longitude %> };
      map = new google.maps.Map(
        document.getElementById('map-canvas'),
        {
          center: location,
          zoom: 12
       }
      );

      var marker = new google.maps.Marker({
         position: location,
         map: map
      });
    }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCyo_TTVJ_17KjZr5Q2eb07CjuAQ6CZj_U&callback=initMap" async defer></script>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">

<h3 class="text-center">Create an account to add sales to favorites and receive the latest sale updates!</h3>

<%= form_for(@user, html: { class: 'form-horizontal'}) do |f| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>
        prohibited this user from being saved:</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>

  <div class="field form-group">
    <%= f.label :username, class: 'col-md-2 control-label' %>
    <%= f.text_field :username, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :password, class: 'col-md-2 control-label' %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :email, class: 'col-md-2 control-label' %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>
  <div class="form-check">
    <label class="form-check-label">
      <input class="form-check-input" type="checkbox" value="">
    Receive email notifications about sales in my area!
    </label>
  </div>
  <div class="actions form-group text-center">
    <%= f.submit "Create account", class: 'btn btn-default' %>
  </div>
<% end %>

<h4 class="text-center">Already Registered?  <%= link_to "Log in!", login_path %></h4>
<br>
<h4 class="text-center"><%= link_to 'Back', estatesales_path %></h4>
</div>
</div>

app/views/users/new_lister.html.erb
  <p>
     <%= f.select(:type, [["Shopper"], ["Lister"]]) %>
  </p>

  <p>
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </p>
  <p>
    <%= f.label :owner_name %>
    <%= f.text_field :owner_name %>
  </p>
  <p>

   <!--  Make url_field? -->
    <%= f.label :company_website %>
    <%= f.url_field :company_url %>
  </p>
  <p>
    <%= f.label :phone_number %>
    <%= f.telephone_field :phone_number %>
  </p>