config/routes.rb
Rails.application.routes.draw do

  root 'estatesales#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :estatesales do
    resources :images, :only => [:create, :destroy]
  end
  resources :favorite_sales
  resources :users
  get 'companies' => 'companies#index'
  get 'list' => 'estatesales#list'  # to advertise/list a sale

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/estatesale.rb
class Estatesale < ActiveRecord::Base
  validates_presence_of :title, :address, :city, :state, :zip_code, :start_date, :end_date, :times, :description, :forms_of_payment
  validates :title, uniqueness: true
  geocoded_by :full_address
  after_validation :geocode

# For Carrierwave photos:
  attr_accessor :photos
  mount_uploaders :images, ImagesUploader
  serialize :images, JSON


  belongs_to :lister
  has_many :favorites
  has_many :shoppers, through: :favorites


# To determine distance from zip code input:
  def distance_from(from)
    GoogleDistanceService.get_distance(from, full_address).round(2)
  end

  def full_address
    [address, city, state, zip_code].join(", ")
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  # belongs_to :shopper
  # belongs_to :estatesale
  belongs_to :favorited, polymorphic: true
  belongs_to :user

  #######
  belongs_to :shopper

end

app/models/lister.rb
class Lister < User
  #added
  has_many :estatesales
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorites
end

app/models/shopper.rb
class Shopper < User
  #added
  # has_many :favorites
  # has_many :estatesales, through: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :username, :password, :email
  validates_uniqueness_of :username, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "Please enter a valid email address."
  validates_length_of :username, :minimum => 3, :message => "Username must be at least 3 characters."
  validates_length_of :password, :in => 6..20, :message => "must be between 6-20 characters."
  has_secure_password

  # Added:
  has_many :favorites
  has_many :favorite_sales, through: :favorites, source: :favorited, source_type: 'Estatesale'

  has_many :notes, through: :favorites


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   # makes methods available to views:
   helper_method :current_user, :logged_in?, :admin?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Returns the current logged-in user, if any.
  def current_user
    current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns T if the user is logged in; F otherwise.
  def logged_in?
    !current_user.nil?
  end

  def admin?
    current_user && current_user.admin?
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
end

app/controllers/favorite_sales_controller.rb
class FavoriteSalesController < ApplicationController
  before_action :set_sale

  def index
    @favorites = current_user.favorite_sales
    # @fav = Favorite.where(favorited_id: @sale.id, user_id: current_user.id)
    @sale = Estatesale.find(params[:sale_id] || params[:id])
  end

  def show
    @favorites = current_user.favorite_sales
  end

  def create
    if Favorite.create(favorited: @sale, user: current_user)
      respond_to do |format|
        format.html { redirect_to @sale, notice: 'Sale has been added to favorites!'}
        format.js
      end
    else
      redirect_to @sale, alert: 'Something went wrong!'
    end
  end

  def destroy
    Favorite.where(favorited_id: @sale.id, user_id: current_user.id).destroy
    redirect_to favorite_sales_path, notice: 'Sale is no longer in favorites'
  end

  private

  def set_sale
    @sale = Estatesale.find(params[:sale_id] || params[:id])
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_estate_sale

  def create
    add_more_images(images_params[:images])
    flash[:error] = "Failed uploading images" unless @sale.save
    redirect_to :back
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    flash[:error] = "Failed to delete image." unless @sale.save
    redirect_to :back
  end

  private

  def set_estate_sale
    @sale = Estatesale.find(params[:id])
  end

  def add_more_images(new_images)
    images = @sale.images
    images += new_images
    @sale.images = images
  end

  def remove_image_at_index(index)
    remaining_images = @sale.images # copy the array
    deleted_image = remaining_images.delete_at(index) # delete the target image
    # deleted_image.try(:remove!) # delete image from S3
    @sale.images = remaining_images # re-assign back
  end

  def images_params
    params.require(:estatesale).permit({images: []})
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @note = Note.new
  end

  def create
    if Note.create(favorited: @sale, user: current_user)
      redirect_to favorite_sales_path
    end
  end

  def edit
  end

  def delete
  end

  private

    def note_params
      params.require(:note).permit(:description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create  #creates session for returning user
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      respond_to do |format|
        format.html { redirect_to estatesales_path }
        format.json
      end
    else
      # flash.now[:danger] = 'Invalid email/password combination'
      render 'new'  #goes to sessions/new
    end
  end

  def destroy  #logs out user
    session[:user_id] = nil
    redirect_to estatesales_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   #Sign Up For New Users
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to estatesales_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:type, :username, :password, :email, :company_name, :owner_name, :company_url, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/estatesale_helper.rb
module EstatesaleHelper



end

app/helpers/favorite_sales_helper.rb
module FavoriteSalesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper

   # Returns the current logged-in user, if any.
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns T if the user is logged in; F otherwise.
  def logged_in?
    !current_user.nil?
  end

end

app/views/favorite_sales/create.js.erb
$('.add-fav').on('click', function () {
  // event.preventDefault();
  $('#empty').toggle();
  $('#filled').css('visibility', 'visible')
  $('#filled').css('color', 'yellow' )


})

 $('.add-fav').replaceWith('Favorite Added!');

app/views/favorite_sales/index.html.erb
<!-- SHOWS ALL FAVORITED SALES -->

<h2 class="text-center"><%= current_user.username %>'s Favorite Sales: </h2>

<table class="table table-hover table-responsive">
  <thead class="thead-default">
    <tr>
      <td><h3><strong>Dates / Times</strong></h3></td>
      <td><h3><strong>Sale Name / Company</strong></h3></td>
      <td><h3><strong>Location</strong></h3></td>
      <td><h3><strong>Distance</strong></h3></td>
      <td><h3><strong>Notes</strong></h3></td>
    </tr>
  </thead>
  <tbody>
    <hr>
      <% @favorites.each do |f| %>
        <tr>
          <td><%= f.start_date%> - <%= f.end_date%><br><%= f.times%></td>
          <td><%= link_to f.title, estatesale_path(f) %><br>Last updated: <%=f.updated_at.strftime("%m.%d.%y") %></td>
          <td><%=f.address%><br><%=f.city%>, <%=f.state%>  <%=f.zip_code%></td>

          <td>  <!-- Need to add distance here:  -->
            <% if params[:zip_code].present? %>
              <%= @sale.distance_from(params[:zip_code]) %> miles
            <% end %>
          </td>
             <!--  Need to re-work notes part -->
          <td>
            <% @notes.each do |note| %>
              <%= note.description %>
            <% end %>
            <!-- Notes: <input type="text" name="notes"><input type="submit" value="Save"> -->
          </td>

          <td><%= link_to 'Remove', favorite_sale_path(f), method: :delete, data: { confirm: 'Are you sure?'} %></td>
        </tr>
      <%end%>

 <!-- <td>Listed by: favorite.estatesale.company.company_name</td> -->

  </tbody>
</table>