config/routes.rb
Rails.application.routes.draw do

  root 'estatesales#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'
  resources :estatesales do
    resources :images, :only => [:create, :destroy]
  end
  resources :favorite_sales
  resources :users
  get 'companies' => 'companies#index'
  get 'list' => 'estatesales#list'  # to advertise/list a sale

end

app/models/company.rb
class Company < ActiveRecord::Base
end

app/models/estatesale.rb
class Estatesale < ActiveRecord::Base
  validates_presence_of :title, :address, :city, :state, :zip_code, :start_date, :end_date, :times, :description, :forms_of_payment
  validates :title, uniqueness: true
  geocoded_by :full_address
  after_validation :geocode

# For Carrierwave photos:
  attr_accessor :photos
  mount_uploaders :images, ImagesUploader
  serialize :images, JSON


  belongs_to :lister
  has_many :favorites
  has_many :shoppers, through: :favorites


# To determine distance from zip code input:
  def distance_from(from)
    GoogleDistanceService.get_distance(from, full_address).round(2)
  end

  def full_address
    [address, city, state, zip_code].join(", ")
  end

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  # belongs_to :shopper
  # belongs_to :estatesale
  belongs_to :favorited, polymorphic: true
  belongs_to :user

  #######
  belongs_to :shopper

end

app/models/lister.rb
class Lister < User
  #added
  has_many :estatesales
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorites
end

app/models/shopper.rb
class Shopper < User
  #added
  # has_many :favorites
  # has_many :estatesales, through: :favorites
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :username, :password, :email
  validates_uniqueness_of :username, :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "Please enter a valid email address."
  validates_length_of :username, :minimum => 3, :message => "Username must be at least 3 characters."
  validates_length_of :password, :in => 6..20, :message => "must be between 6-20 characters."
  has_secure_password

  # Added:
  has_many :favorites
  has_many :favorite_sales, through: :favorites, source: :favorited, source_type: 'Estatesale'

  has_many :notes, through: :favorites


end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_estate_sale

  def create
    add_more_images(images_params[:images])
    flash[:error] = "Failed uploading images" unless @sale.save
    redirect_to :back
  end

  def destroy
    remove_image_at_index(params[:id].to_i)
    flash[:error] = "Failed to delete image." unless @sale.save
    redirect_to :back
  end

  private

  def set_estate_sale
    @sale = Estatesale.find(params[:id])
  end

  def add_more_images(new_images)
    images = @sale.images
    images += new_images
    @sale.images = images
  end

  def remove_image_at_index(index)
    remaining_images = @sale.images # copy the array
    deleted_image = remaining_images.delete_at(index) # delete the target image
    # deleted_image.try(:remove!) # delete image from S3
    @sale.images = remaining_images # re-assign back
  end

  def images_params
    params.require(:estatesale).permit({images: []})
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def new
    @note = Note.new
  end

  def create
    if Note.create(favorited: @sale, user: current_user)
      redirect_to favorite_sales_path
    end
  end

  def edit
  end

  def delete
  end

  private

    def note_params
      params.require(:note).permit(:description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create  #creates session for returning user
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      respond_to do |format|
        format.html { redirect_to estatesales_path }
        format.json
      end
    else
      # flash.now[:danger] = 'Invalid email/password combination'
      render 'new'  #goes to sessions/new
    end
  end

  def destroy  #logs out user
    session[:user_id] = nil
    redirect_to estatesales_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

   #Sign Up For New Users
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to estatesales_path
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:type, :username, :password, :email, :company_name, :owner_name, :company_url, :phone_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/estatesale_helper.rb
module EstatesaleHelper



end

app/helpers/favorite_sales_helper.rb
module FavoriteSalesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

end

app/helpers/users_helper.rb
module UsersHelper

   # Returns the current logged-in user, if any.
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns T if the user is logged in; F otherwise.
  def logged_in?
    !current_user.nil?
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Estates-to-Date</title>

    <script src="https://use.fonticons.com/65d4015f.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body style="background-color:#000">
      <div class="jumbotron">
        <div class="container">

            <%= image_tag("logo.png", alt: "logo", :id => "logo") %>
          <p class="header-subtext">Estate Sales & Auctions in the Seattle area</p>
        </div>
      </div>
      <div class="container" id="nav-bar">
         <nav class="navbar navbar-inverse" role="navigation" style="background-color: #002d1b;">
          <div class="container">
            <div class="navbar-header">
              <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#left-nav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
            </div>
            <div class="navbar-collapse collapse" id="left-nav">
              <ul class="nav nav-pills navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item"><%= link_to 'Find Estate Sales', estatesales_path %></li>
                <li class="nav-item"><%= link_to 'Hire a Company', companies_path %></li>
                <li class="nav-item"><%= link_to 'List your Sale', list_path %></li>
                <li class="nav-item"><a href='#'>Contact Us</a></li>
              </ul>

              <ul class="nav nav-pills navbar-nav navbar-right" id="right-nav">
                <% if !logged_in? %>
                  <li class="nav-item"><%= link_to 'Sign Up', new_user_path %></li>
                  <li class="nav-item"><%= link_to 'Log In', login_path %></li>
                <% end %>
                <%  if logged_in? %>
                  <li class="nav-item"><%= link_to 'Log Out', logout_path %></li>
                <% end %>
              </ul>
            </div>


          </div>
        </nav>
      </div>

          <!-- Need to add these later: -->
          <!-- <a href="#">Auctions</a> -->
          <!-- <a href="#">Out & About</a> -->



    <div id="main-container" class="container clearfix">


          <%= yield %>

    </div>

  </body>
</html>